services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
     - elk
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    command: filebeat -e -strict.perms=false
    restart: unless-stopped
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - elk
    depends_on:
       - kibana
    links:
       - elasticsearch
       - kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 1s
      timeout: 30s
      retries: 20
networks:
  elk:
    driver: bridge
